export const PricingList = [
  {
    imgUrl: 'images/icon_scheduling.svg',
    title: 'Scheduling',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci provident praesentium quia',
    price: 2.5,
    det1: 'Lorem ipsum dolor sit amet.',
    annualPlan: 'No Annual plan',
    url: '/',
    tickImg: 'images/tick.svg',
    detail1: 'Employee Scheduling',
    detail2: 'Employee Scheduling',
    detail3: 'Employee Scheduling',
    detail4: 'Employee Scheduling',
    detail5: 'Employee Scheduling',
    detail6: 'Employee Scheduling',
    learnMore: '/',
  },
  {
    imgUrl: 'images/icon_scheduling.svg',
    title: 'Time and Attendance',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci provident praesentium quia',
    price: 2.5,
    det1: 'Lorem ipsum dolor sit amet.',
    annualPlan: 'No Annual plan',
    url: '/',
    tickImg: 'images/tick.svg',
    detail1: 'Employee Scheduling',
    detail2: 'Employee Scheduling',
    detail3: 'Employee Scheduling',
    detail4: 'Employee Scheduling',
    detail5: 'Employee Scheduling',
    detail6: 'Employee Scheduling',
    learnMore: '/',
  },
  {
    imgUrl: 'images/icon_scheduling.svg',
    title: 'Premium',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci provident praesentium quia',
    price: 2.5,
    det1: 'Lorem ipsum dolor sit amet.',
    annualPlan: 'No Annual plan',
    url: '/',
    tickImg: 'images/tick.svg',
    detail1: 'Employee Scheduling',
    detail2: 'Employee Scheduling',
    detail3: 'Employee Scheduling',
    detail4: 'Employee Scheduling',
    detail5: 'Employee Scheduling',
    detail6: 'Employee Scheduling',
    learnMore: '/',
  },
  {
    imgUrl: 'images/icon_scheduling.svg',
    title: 'Enterprise',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci provident praesentium quia',
    price: 2.5,
    det1: 'Lorem ipsum dolor sit amet.',
    annualPlan: 'No Annual plan',
    url: '/',
    tickImg: 'images/tick.svg',
    detail1: 'Employee Scheduling',
    detail2: 'Employee Scheduling',
    detail3: 'Employee Scheduling',
    detail4: 'Employee Scheduling',
    detail5: 'Employee Scheduling',
    detail6: 'Employee Scheduling',
    learnMore: '/',
  },
];
